### ISSUE TITLE
Where are 'vima-0d8k.json', 'vima-8k.json' and 'vima-80k.json'?

### ISSUE THREAD

**Issue by RogerRafa** [LostXine/LLaRA#1]
In the repository, I couldn't find 'vima-0d8k.json', 'vima-8k.json', and 'vima-80k.json'.

**Comment by LostXine** [comment]
Hi @RogerRafa  

Sorry for the confusion. I've uploaded the missing files. Please pull the main branch, and you should be able to find them now. It appears they were accidentally removed during code cleanup.

Thank you for your understanding.

Best regards,

**Comment by RogerRafa** [comment]
Thank you！
