### ISSUE TITLE
read trajectory.pkl error

### ISSUE THREAD

**Issue by zhouzhubin** [LostXine/LLaRA#4]
Thanks for releasing the code for the great work. 
I download VIMA data, when i read trajectory.pkl will appear 
ModuleNotFoundError: No module named 'vimasim'  error. 
How should I solve this?  Thanks!

**Comment by LostXine** [comment]
Hi @zhouzhubin ,

Could you help me confirm that you ‘ve successfully installed VIMABench? https://github.com/vimalabs/VIMABench

Thanks,

**Comment by zhouzhubin** [comment]
Thank you for your reply. I didn't install this VIMABench, i will try it . Thanks again

**Comment by LostXine** [comment]
Thanks, please reopen this issue if it does not work.
