### ISSUE TITLE
Where can we download the weights for RT2?

### ISSUE THREAD

**Issue by erjiaxiao** [LostXine/LLaRA#6]
Hello @LostXine, could I ask where we can download the weights for RT2?

**Comment by LostXine** [comment]
Hi @erjiaxiao ,
Let me get them uploaded in 1-2 days. May I know which particular model you are interested in? 
Thanks,

**Comment by erjiaxiao** [comment]
Thanks for your excellent work! I am intrigued by models that demonstrate remarkable capabilities in visual cognition and inference, such as LLaRA, RT-2, and RT-2-X.

**Comment by LostXine** [comment]
Hi @erjiaxiao 

The original RT-2 weight is not public yet as far as I know. Our baseline `D-RT2 Style` which follows the design principle and was trained on VIMA-80k is now available at [this huggingface link](https://huggingface.co/variante/llava-1.5-7b-llara-D-RT2-Style-VIMA-80k).

Thank you.

**Comment by erjiaxiao** [comment]
@LostXine Thanks a lot!
